version: '3'

services:
  opennsa-db:
    image: postgres:9.6.5
    restart: always
    volumes:
      - ${SCHEMA_FILE}:/docker-entrypoint-initdb.d/schema.sql:ro
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "opennsa" ]
      timeout: 45s
      interval: 10s
      retries: 10
    network_mode: "host"


  opennsa:
    image: colbysawyer17/opennsa3:latest
    depends_on:
      opennsa-db:
        condition: service_healthy
    network_mode: "host"
    links:
      - opennsa-db
    volumes:
      - ${OPENNSA_CONF_LOC}:/home/opennsa/opennsa3/config:ro
      - ${OPENNSA_TAC_LOC}:/home/opennsa/opennsa3/opennsa-docker3.tac:ro



