version: '3'

services:
  opennsa:
    image: colbysawyer17/opennsa3:latest
    volumes:
      - ${OPENNSA_CONF_LOC}:/home/opennsa/opennsa/config:ro
      - ${OPENNSA_TAC_LOC}:/home/opennsa/opennsa-docker3.tac:ro
    network_mode: "host"



